export const projects = [
  {
    name: "Babershop",
    category: "Babershop",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
  },
  {
    name: "Ecommerce",
    category: "Ecommerce",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
  },
  {
    name: "Muñoz & Asociados",
    category: "Muñoz & Asociados",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
  },
  {
    name: "Babershop",
    category: "Babershop",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
  },
  {
    name: "Ecommerce",
    category: "Ecommerce",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
  },
  {
    name: "Muñoz & Asociados",
    category: "Muñoz & Asociados",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
  },
  {
    name: "Babershop",
    category: "Babershop",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
  },
  {
    name: "Ecommerce",
    category: "Ecommerce",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
  },
  {
    name: "Muñoz & Asociados",
    category: "Muñoz & Asociados",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
  },
];
