export const projects = [
  {
    name: "Babershop",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
    date: "29. August 2023",
  },
  {
    name: "Ecommerce",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
    date: "29. August 2023",
  },
  {
    name: "Muñoz & Asociados",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
    date: "29. August 2023",
  },
  {
    name: "Babershop",
    category: "Babershop",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
    date: "29. August 2023",
  },
  {
    name: "Ecommerce",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
    date: "29. August 2023",
  },
  {
    name: "Muñoz & Asociados",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
    date: "29. August 2023",
  },
  {
    name: "Babershop",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
    date: "29. August 2023",
  },
  {
    name: "Ecommerce",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
    date: "29. August 2023",
  },
  {
    name: "Muñoz & Asociados",
    category: "Design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
    date: "29. August 2023",
  },
];
