export const projects_EN = [
  {
    name: "Portafolio_v1",
    category: "design",
    image: "https://i.imgur.com/CN9S1FO.png",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    date: "19 March 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind", "Javascript"],
  },
  {
    name: "Babershop",
    category: "design",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
    date: "30 June 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind", "Javascript", "Node"],
  },
  {
    name: "Ecommerce",
    category: "design",
    image: "https://i.imgur.com/L7T2wmf.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
    date: "10 July 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
  },
  {
    name: "Hoshi Creative",
    category: "design",
    image: "https://i.imgur.com/eFmKV76.png",
    url: "https://www.hoshicreative.art/",
    github: "https://www.hoshicreative.art/",
    date: "10 August 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
  },
  {
    name: "Dogur",
    category: "design",
    image: "https://i.imgur.com/LsbEqGb.png",
    url: "https://dogur.vercel.app/",
    github: "https://github.com/Basso-23/Dogur",
    date: "19 September 2023",
    tech1: "Astro",
    tech2: "Tailwind",
    tech: ["Astro", "Tailwind", "Javascript"],
  },
  {
    name: "Muñoz & Asociados",
    category: "design",
    image: "https://i.imgur.com/rCI8l6b.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
    date: "29 October 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
  },
  {
    name: "Voting system",
    category: "full-stack",
    image: "https://i.imgur.com/78vwRho.png",
    url: "https://github.com/Basso-23/Sistema_Elecciones",
    github: "https://github.com/Basso-23/Sistema_Elecciones",
    date: "4 May 2024",
    tech1: "Next",
    tech2: "React",
    tech: [
      "Next",
      "React",
      "Tailwind",
      "Shadcn",
      "Firebase",
      "Javascript",
      "Node",
    ],
  },
];

//tech: [
//{ skill: "Firebase" },
//{ skill: "Next" },
//{ skill: "React" },
//{ skill: "Tailwind" },
//{ skill: "Javascript" },
//{ skill: "Node" },
//{ skill: "Shadcn" },
//],
