export const projects_ES = [
  {
    name: "Portafolio_v1",
    category: "diseño",
    image: "https://i.imgur.com/CN9S1FO.png",
    url: "https://portfolio-v2-three-woad.vercel.app/",
    github: "https://github.com/Basso-23/Portfolio_v2",
    date: "19 Marzo 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind", "Javascript"],
    summary: "",
  },
  {
    name: "Babershop",
    category: "diseño",
    image: "https://i.imgur.com/u7KKJmO.png",
    url: "https://barbershop-woad.vercel.app/",
    github: "https://github.com/Basso-23/Barbershop",
    date: "30 Junio 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind", "Javascript", "Node"],
    summary: "",
  },
  {
    name: "Ecommerce",
    category: "diseño",
    image: "https://i.imgur.com/L7T2wmf.png",
    url: "https://estructura-ecommerce.vercel.app/",
    github: "https://github.com/Basso-23/Estructura_Ecommerce",
    date: "10 Julio 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
    summary: "",
  },
  {
    name: "Hoshi Creative",
    category: "diseño",
    image: "https://i.imgur.com/eFmKV76.png",
    url: "https://www.hoshicreative.art/",
    github: "https://www.hoshicreative.art/",
    date: "10 Agosto 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
    summary: "",
  },
  {
    name: "Dogur",
    category: "Diseño",
    image: "https://i.imgur.com/LsbEqGb.png",
    url: "https://dogur.vercel.app/",
    github: "https://github.com/Basso-23/Dogur",
    date: "19 Septiembre 2023",
    tech1: "Astro",
    tech2: "Tailwind",
    tech: ["Astro", "Tailwind", "Javascript"],
    summary: "",
  },
  {
    name: "Muñoz & Asociados",
    category: "diseño",
    image: "https://i.imgur.com/rCI8l6b.png",
    url: "https://pagina-contador-abogado.vercel.app/",
    github: "https://github.com/Basso-23/Abogados_Firma",
    date: "29 Octubre 2023",
    tech1: "Next",
    tech2: "React",
    tech: ["Next", "React", "Tailwind"],
    summary: "",
  },
  {
    name: "Sistema de votación",
    category: "full-stack",
    image: "https://i.imgur.com/78vwRho.png",
    url: "https://github.com/Basso-23/Sistema_Elecciones",
    github: "https://github.com/Basso-23/Sistema_Elecciones",
    date: "4 Mayo 2024",
    tech1: "Next",
    tech2: "React",
    tech: [
      "Next",
      "React",
      "Tailwind",
      "Shadcn",
      "Firebase",
      "Javascript",
      "Node",
    ],
    summary: "",
  },
];
